### ISSUE TITLE
Placement of server runner

### ISSUE THREAD

**Issue by kokujin** [arvindr21/slush-express#1]
Nice generator. Just out of curiosity, why do you start the application from 

```
bin/www/
```

instead of directly from the root folder?

**Comment by arvindr21** [comment]
@kokujin Thanks. 

This is the standard template scaffolded using express generator. So left it as is. 

I guess, the server start/stop is a key thing & no one should be able to do it easily and that is why `www` script is put inside the `bin` folder  :).

If you find out the real reason, do let me know.

Thanks.
