### ISSUE TITLE
use of  npm i -g gulp slush slush-express

### ISSUE THREAD

**Issue by Jeet1994** [arvindr21/slush-express#2]
I am using your tutorial at Sitepoint for sentiment analysis on Twitter on Node Js.

Here is the error:

C:\Users\home\Desktop\jeet>npm i -g gulp slush slush-express
C:\Users\home\AppData\Roaming\npm\slush -> C:\Users\home\AppData\Roaming\npm\nod
e_modules\slush\bin\slush.js
npm ERR! Error: EBUSY, open 'C:\Users\home\AppData\Roaming\npm\node_modules\gulp
\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\
globule\node_modules\minimatch\node_modules\sigmund\package.json'
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "i" "-g" "gulp" "slush" "slush-express"

npm ERR! cwd C:\Users\home\Desktop\jeet
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\home\AppData\Roaming\npm\node_modules\gulp\node_modules\v
inyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_mo
dules\minimatch\node_modules\sigmund\package.json
npm ERR! code EBUSY
npm ERR! errno 10
npm ERR! not ok code 0

**Comment by arvindr21** [comment]
This seems to be a permission issue on the file

``` bash
open 'C:\Users\home\AppData\Roaming\npm\node_modules\gulp
\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\
globule\node_modules\minimatch\node_modules\sigmund\package.json'
```

Take a look at [Node.js and File System on Windows - EBUSY error](http://stackoverflow.com/questions/10747347/node-js-and-file-system-on-windows-ebusy-error)

Try the following

``` bash
$ npm unintstall -g gulp
#.... once done
$ npm install -g gulp
```
